server:
  port: 8080

spring:
  datasource:
    name: cloudplatform
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudplatform?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikariCP
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      enabled: true # 开启文件上传
      file-size-threshold: 2000KB # 文件写入磁盘的阈值
      max-file-size: 1000MB
      max-request-size: 3000MB # 最大请求值大小

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

filemanager:
  # 文件上传的路径
  file: /Users/linhaiyang/Downloads/Misc/
  # 文件下载的路径,需要自己新建到Download文件夹
  downloadFile: /Users/linhaiyang/Downloads/Misc/Download/Download.zip
  # 文件打包的路径(中转)
  zipFile: /Users/linhaiyang/Downloads/Misc/Zip

docker:
#  # docker连接
#  dockerConnect: tcp://localhost:2375
#  # 本地挂载目录的父目录的路径
#  baseBindDirlocal: /Users/linhaiyang/Downloads/Misc/
#  # 容器中挂在的目录的路径
#  bindDirContainer: /home/coder/workspace/
  #在线ide开始的端口号
  startport: 10000

IDE:
  # IDE的访问路径,例如:  http://localhost:10000/?folder=/home/coder/workspace
  path: /?folder=/home/coder/workspace
  ip: 127.0.0.1