server:
  port: 8080

spring:
  datasource:
    name: cloudplatform
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudplatform?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikariCP
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      enabled: true # 开启文件上传
      file-size-threshold: 2000KB # 文件写入磁盘的阈值
      max-file-size: 1000MB
      max-request-size: 3000MB # 最大请求值大小

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 文件上传的路径
file: /Users/linhaiyang/Downloads/Misc/
# 文件下载的路径,需要自己新建到Download文件夹
downloadFile: /Users/linhaiyang/Downloads/Misc/Download/Download.zip
# 文件打包的路径(中转)
zipFile: /Users/linhaiyang/Downloads/Misc/Zip
